global using BuildingBlocks.Behevior;
global using Carter;
global using Basket.API.Exceptions;
global using Basket.API.Models;
global using Marten;
global using Basket.API.Data;
global using Basket.API.Models;
global using BuildingBlocks.CQRS;
global using FluentValidation;